### ISSUE TITLE
Not Working Protractor Multi Row Selection through CONTROL Key in Firefox Browser

### ISSUE THREAD

**Issue by A-Kavin** [IgorSasovets/protractor-firefox-support#11]
System:
Firefox Version: 91.0.2 (64-bit)
Protractor Version: 7.0.0
Typescript
Webdriver updated

Issue in Firefox Browser:
WebDriverError: HTTP method not allowed

Code:
async multiRowSelection(expectRow2:any,expectRow3:any){
		await this.mainDiv.each(async (item)=>{
			if(await item.getAttribute('row-index')===expectRow2){
				await browser.actions().sendKeys(protractor.Key.CONTROL+await item.click()).perform()
			}
        });
		await this.mainDiv.each(async (item)=>{
			if(await item.getAttribute('row-index')===expectRow3){
				await browser.actions().sendKeys(protractor.Key.CONTROL+await item.click()).perform()
				.then(async() =>{
					await browser.actions().click(protractor.Button.RIGHT).perform();
				});
			}
        });
}

**Comment by IgorSasovets** [comment]
Hi @A-Kavin , this lib does not provide implementation of `sendKeys` method and I'm not going to add this action in future.

**Comment by IgorSasovets** [comment]
@A-Kavin please take a look at [this StackOverflow topic](https://stackoverflow.com/questions/596481/is-it-possible-to-simulate-key-press-events-programmatically). You can also investigate functions that are triggered when you perform multiselect manually and try to simulate these actions using `dispatchEvent` method

**Comment by IgorSasovets** [comment]
Closed due to inactivity
