### ISSUE TITLE
with the example, DragAndDrop, performDnD isn´t found and is missing a ';'

### ISSUE THREAD

**Issue by carodrigues** [IgorSasovets/protractor-firefox-support#4]
I'm working on the implementation of "protractor-firefox-support", but, as i'm new with protractor, i'm facing some problems.

Do you have a compete example?

with the example, DragAndDrop, performDnD isn´t found and is missing a ';'

**Comment by IgorSasovets** [comment]
Hi, @carodrigues! Thanks for taking a look at this. I'm a bit busy now but I'll add links to complete examples for better understanding. Also, one more question: you mean performDnD from examples folder?

**Comment by IgorSasovets** [comment]
I added more examples of usage. Hope it'll help you. But you can ask more questions in case you need some help.

**Comment by Venkateshkumar-Selvarajan** [comment]
Hi @IgorSasovets. I need to perform a double click action.

**Comment by IgorSasovets** [comment]
Hi, @Venkateshkumar-Selvarajan ! Could you please share a test example with a link to the application where I can test this?

**Comment by Venkateshkumar-Selvarajan** [comment]
@IgorSasovets Here is the link to the application: [https://artoftesting.com/sampleSiteForSelenium.html]

**Comment by PoovinPR** [comment]
@IgorSasovets Can I pass a selector as the parameter to the **mouseMove** function instead of passing the X, Y coordinates?

**Comment by IgorSasovets** [comment]
@PoovinPR , current implementation of the lib doesn't support it. Please check this [link](https://api.jquery.com/mousemove/)

**Comment by IgorSasovets** [comment]
@Venkateshkumar-Selvarajan , for what element you want perform a double click?

**Comment by Venkateshkumar-Selvarajan** [comment]
@IgorSasovets I have to perform a double click on the button with the button text **Double-click to generate alert box**

**Comment by IgorSasovets** [comment]
@PoovinPR , if you're interested in, I can provide you an example how to achieve mentioned by you behavior

**Comment by IgorSasovets** [comment]
@Venkateshkumar-Selvarajan , you have to use `dispatchEvent` method with the following payload
```
{selector: '#dblClkBtn', eventType: 'dblclick'}
```
It looks like this:
```
await browser.executeScript(support.dispatchEvent, {selector: '#dblClkBtn', eventType: 'dblclick'});
```

For more examples of usage please take a look [this link](https://github.com/IgorSasovets/protractor-firefox-support/blob/master/examples/dispatchEvent.js)

**Comment by PoovinPR** [comment]
@IgorSasovets Yes, Please provide me an example for mouseMove without specifying coordinates but specifying selectors.

**Comment by IgorSasovets** [comment]
@PoovinPR , you should add small precondition for retrieving target element coordinates like below:
```
const script = 'return document.querySelector(arguments[0]).getBoundingClientRect();';
const coordinates = await browser.executeScript(script, <element_selector>);
await browser.executeScript(support.mouseMove, {x: Math.floor(coordinates.x), y: Math.floor(coordinates.y)});
```
By the way, I could add this feature into the next release.

**Comment by Venkateshkumar-Selvarajan** [comment]
@IgorSasovets for the double click event. how can I find the **eventType: 'dblclick'**. In the Latest angular version, we can not find the eventType.

**Comment by IgorSasovets** [comment]
@Venkateshkumar-Selvarajan , could you please provide an example of an issue because I don't understand what exactly wrong. Did you try provided by me code? In my case it works. If you your question relates to approach of finding required event types then I can provide you an example.
