### ISSUE TITLE
How does one go about with doubleClick() on Firefox?

### ISSUE THREAD

**Issue by priyankashriram** [IgorSasovets/protractor-firefox-support#6]
How do I get doubleClick() to work on Firefox with protractor?

**Comment by IgorSasovets** [comment]
Hi, @priyankashriram ! Could you please share more details about your config, test application? In general, take a look at [dispatchEvent method](https://github.com/IgorSasovets/protractor-firefox-support#dispatcheventcomplete-example-here) and [rightClick](https://github.com/IgorSasovets/protractor-firefox-support#opencontextmenurightmouseclick-complete-example-here)

**Comment by IgorSasovets** [comment]
@priyankashriram , feel free to reopen this issue or create a new one if you still have issues
