### ISSUE TITLE
How to use this code for double click and hover

### ISSUE THREAD

**Issue by praveenngp15** [IgorSasovets/protractor-firefox-support#7]
How to use this library for double click and hover. 

Can you give some code snippet?

**Comment by IgorSasovets** [comment]
Hi, @praveenngp15 ! Here are the methods that should help you with these issues:
**double click**
Below is an example of using `dblclick` event. In this particular case we want to click on element with
selector `.mat-expansion-panel-header` :
```
it('Should expand panel with \'Personal data\'', async() => {
      await browser.executeScript(support.dispatchEvent, {selector: '.mat-expansion-panel-header',
                eventType: 'dblclick'});
      expect($('input[placeholder=\'First name\']').isPresent()).toBe(true);
 });
```
**hover**
Please review event listeners for the element that will receive hover event. It will help you to choose a correct event type. To dispatch this event you can use this code
```
describe('Dispatch mouseover event to element', () => {
        beforeAll(async() => {
            const emailButton = $('.TK-Aside-Menu-Item.TK-bn');
            browser.ignoreSynchronization = true;
            await browser.get(params.mouseOverDemo);
            await browser.wait(EC.elementToBeClickable(emailButton), 7000);
        });
        it('Should open element context menu using mouseover event', async() => {
            const contextMenuOption = element(by.cssContainingText('ul.TK-Dropdown a.TK-Dropdown-Link',
                'jQuery'));
            await browser.executeScript(support.dispatchEvent, {selector: '.TK-Menu-Item',
                eventType: 'mouseenter', elementIndex: 1, isMouseEvent: true});
            await browser.sleep(500);
            expect(contextMenuOption.isPresent()).toBe(true);
        });
    });
```
In the above example, `mouseenter` event will do the trick.
More examples are available [here](https://github.com/IgorSasovets/protractor-firefox-support/blob/master/tests/dispatch-event-test.js)

**Comment by IgorSasovets** [comment]
Closed because of inactivity. Feel free to reopen it if the problem still exists

**Comment by praveenngp15** [comment]
Can we use XPath instead of CSS.  or any workaround to use XPath for double click

**Comment by IgorSasovets** [comment]
@praveenngp15 , take a look at [this example](https://stackoverflow.com/questions/10596417/is-there-a-way-to-get-element-by-xpath-using-javascript-in-selenium-webdriver) . You can create your own script based on the repository functions. Only thing that you need is to change the strategy of finding element.
